name: Prune Old Branches
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    # Run the job at 00:00, on day 1 of the month.
    - cron: '0 0 1 * *'
jobs:
  delete-old-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get remote branches
        run: git fetch --prune --unshallow
      - name: Delete old branches
        run: |
          for branch in $(git branch -r --merged | egrep -v "(^|/)HEAD(/|$)" | egrep -v "(^|/)master(/|$)" | egrep -v "(^|/)main(/|$)" | egrep -v "(^|/)develop(/|$)" | tr -d '[:space:]'); do
            if [[ "$(git log -1 --format=%ct $branch)" < "$(date -d '10 seconds ago' +%s)" ]]; then
              run: echo "Deleting branch: ${branch#origin/}\n"
              # git push origin --delete ${branch#origin/}
            fi
          done
