name: Prune Old Branches
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
    # Run the job at 00:00, on day 1 of the month.
    - cron: '0 0 1 * *'
jobs:
  delete-old-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get remote branches
        run: git fetch --prune --unshallow
      - name: Delete old branches
        id: delete-branches
        run: |
          branches=$(git branch -r --merged | egrep -v "(^|/)HEAD(/|$)" | egrep -v "(^|/)master(/|$)" | egrep -v "(^|/)main(/|$)" | tr -d '[ ]')
          deleted_branches=""
          for branch in $branches; do
            if [[ "$(git log -1 --format=%ct $branch)" < "$(date -d '1 second ago' +%s)" ]]; then
              deleted_branch=$(echo $branch | sed 's/[^\/]*\///g')
              git push origin --delete ${branch#*/}
              deleted_branches="$deleted_branches $deleted_branch"
            fi
          done
          echo "Deleted branches: $deleted_branches"
